name: Tests
run-name: Run all tests in a row
on: [push]
jobs:
  hmmJustTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go version
      - name: Run all tests
        run: go test -v ./...